# Generated by Django 5.2 on 2025-04-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
